name: 'Test'

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libgtest-dev libpqxx-dev

      - name: Build project
        run: |
          cmake .
          cmake --build .

      - name: Build and run tests
        run: cmake --build . --target test